# Change these first
owner: MAZ-Techno # Your GitHub organization or username, where this repository lives
repo: status-monitoring-maztech-work # The name of this repository
user-agent: upptime
branch: master

sites:
  - name: Avicenne - LUX
    url: https://avicenne.lu/
    location: Luxembourg
    skipDeleteIssues: true
    assignees:
      - aibrahim89
      - MostafaAshrySOPC
  - name: Mosaique - LUX
    url: https://mosaiquelux.lu/
    location: Luxembourg
    skipDeleteIssues: true
    assignees:
      - aibrahim89
      - MostafaAshrySOPC
  - name: Iredi - LUX
    url: https://iredi.lu/
    location: Luxembourg
    skipDeleteIssues: true
    assignees:
      - aibrahim89
      - MostafaAshrySOPC
  - name: The knowledge venue - EGY
    url: https://theknowledgevenue.com/
    location: Egypt
    skipDeleteIssues: true
    assignees:
      - aibrahim89
      - MostafaAshrySOPC
      - Aymanabelmoaty
  - name: Luxembourg University Press - LUX
    url: https://unipress.lu/
    location: Luxembourg
    skipDeleteIssues: true
    assignees:
      - aibrahim89
      - MostafaAshrySOPC
      - Aymanabelmoaty
  - name: Luxor Library - LUX
    url: https://luxorlibrary.lu/
    location: Luxembourg
    skipDeleteIssues: true
    assignees:
      - aibrahim89
      - MostafaAshrySOPC
      - Aymanabelmoaty
  - name: Grocify Shop - LUX
    url: https://grocify.lu/
    location: Luxembourg
    skipDeleteIssues: true
    assignees:
      - aibrahim89
      - MostafaAshrySOPC
      - Aymanabelmoaty
  - name: Luxy Tech - LUX
    url: https://luxytech.lu/
    location: Luxembourg
    skipDeleteIssues: true
    assignees:
      - aibrahim89
  - name: Lissane School - LUX
    url: https://lissane.lu/
    location: Luxembourg
    skipDeleteIssues: true
    assignees:
      - aibrahim89
      - MostafaAshrySOPC
      - Aymanabelmoaty
  - name: AFMM Mosque - LUX
    url: https://afmm.lu/
    location: Luxembourg
    skipDeleteIssues: true
    assignees:
      - aibrahim89
      - MostafaAshrySOPC
  - name: Manual Therapy Home - LUX
    url: https://manualtherapyhome.com/
    location: Luxembourg
    skipDeleteIssues: true
    assignees:
      - aibrahim89
      - MostafaAshrySOPC
  - name: Joo & M Logistics - EGY
    url: https://joo-m-logistics.com/
    location: Egypt
    skipDeleteIssues: true
    assignees:
      - MostafaAshrySOPC
      - Aymanabelmoaty
  - name: Islam - Joo & M Logistics - EGY
    url: https://islam.joo-m-logistics.com/
    location: Egypt
    skipDeleteIssues: true
    assignees:
      - MostafaAshrySOPC
      - Aymanabelmoaty
  - name: SOPC RH - EGY
    url: https://sopceg.com/
    location: Egypt
    skipDeleteIssues: true
    assignees:
      - MostafaAshrySOPC
      - Aymanabelmoaty
  - name: SUEZ PMC - EGY
    url: https://suezpmc.com/
    location: Egypt
    skipDeleteIssues: true
    assignees:
      - MostafaAshrySOPC
      - Aymanabelmoaty
  - name: Portal SUEZ PMC - EGY
    url: https://portal.suezpmc.com/
    location: Egypt
    skipDeleteIssues: true
    assignees:
      - MostafaAshrySOPC
      - Aymanabelmoaty
  - name: Minaharis - EGY
    url: https://minaharis.com/
    location: Egypt
    skipDeleteIssues: true
    assignees:
      - MostafaAshrySOPC
      - Aymanabelmoaty
  - name: Qasimi Realestate Develop - EGY
    url: https://qasimidevelop.com
    location: Egypt
    skipDeleteIssues: true
    assignees:
      - MostafaAshrySOPC
      - Aymanabelmoaty
  - name: Shabana Gold - EGY
    url: http://app.shabanagold.com/
    _dangerous_insecure: true
    location: Egypt
    skipDeleteIssues: true
    assignees:
      - MostafaAshrySOPC
      - Aymanabelmoaty
      - aibrahim89
  - name: IPv6 Cloudflare DNS
    url: one.one.one.one
    port: 53
    check: tcp-ping
    assignees:
      - aibrahim89

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status-monitoring-maztech-work
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: MAZ status
  theme: light
  introTitle: "**MAZ** is using Uppwork (the open-source) to have uptime monitor and status page, Hosted on GitHub/Pages."
  introMessage: This is a sample status page which uses **real-time** data from [MAZ-Techno GitHub repository](https://github.com/MAZ-Techno/status-monitoring-maztech-work). Resources used — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: https://maz-techno.github.io/status-monitoring-maztech-work
    - title: MAZ-Techno
      href: https://maztechnologies.net/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
