# Change these first
owner: MAZ-Techno # Your GitHub organization or username, where this repository lives
repo: status-monitoring-maztech-work # The name of this repository
user-agent: upptime
branch: master

sites:
  - name: Avicenne - LUX
    url: https://avicenne.lu/
  - name: Mosaique - LUX
    url: https://mosaiquelux.lu/
  - name: Iredi - LUX
    url: https://iredi.lu/
  - name: The knowledge venue - EGY
    url: https://theknowledgevenue.com/
  - name: Luxembourg University Press - LUX
    url: https://unipress.lu/
  - name: Luxor Library - LUX
    url: https://luxorlibrary.lu/
  - name: Grocify Shop - LUX
    url: https://grocify.lu/
  - name: Luxy Tech - LUX
    url: https://luxytech.lu/
  - name: Lissane School - LUX
    url: https://lissane.lu/
  - name: AFMM Mosque - LUX
    url: https://afmm.lu/
  - name: Manual Therapy Home - LUX
    url: https://manualtherapyhome.com/
  - name: Joo & M Logistics - EGY
    url: https://joo-m-logistics.com/
  - name: Islam - Joo & M Logistics - EGY
    url: https://islam.joo-m-logistics.com/
  - name: SOPC RH - EGY
    url: https://sopceg.com/
  - name: SUEZ PMC - EGY
    url: https://suezpmc.com/
  - name: Portal SUEZ PMC - EGY
    url: https://portal.suezpmc.com/
  - name: Minaharis - EGY
    url: https://minaharis.com/
  - name: Qasimi Realestate Develop - EGY
    url: https://qasimidevelop.com
  - name: Shabana Gold - EGY
    url: http://app.shabanagold.com/
  - name: IPv6 Cloudflare DNS
    url: one.one.one.one
    port: 53
    check: tcp-ping

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status-monitoring-maztech-work
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
